config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  
  devise_for :users

  get 'home/show', to: 'home#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true, uniqueness: true
  validates :last_name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

		before_action :sanitize_devise_parameters, if: :devise_controller?

		def sanitize_devise_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
													
		end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  	before_action :authenticate_user!, except: [:index]

  def index
  end

  def show
  	@users=User.all 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class='text-center'>
	<h1>Buy a "zucchini" to get in the club</h1>
	<h2> and Manage your migrations</h2>
</div>
<br>

<h3 class='text-center' class="p-2 text-dark"> <%= link_to "Index of Users", home_show_path %></h3>

app/views/home/show.html.erb
<div class='text-center'>
<h1> List of Zucchinis </h1>
<br>
<% @users.each do |info| %>	
	<h5>First Name: <%= info.first_name %></h5>
	<h5>Last Name: <%= info.last_name %></h5>
	<h5>Email : <%= info.email %></h5>

 -------------------------------
  <br>
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClubPrive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous"><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to "Club Privé", home_index_path %></h5>
      
      <nav class="my-2 my-md-0 mr-md-3">
        
        <% if user_signed_in? %>
        <span class="p-2 text-dark"> </span>
        <span class="p-2 text-dark"> <%= link_to "Index of Users", home_show_path %></span>
        <span class="btn btn-outline-primary"> <%= link_to "Edit Account",  edit_user_registration_path %></span>
        <span class="btn btn-outline-primary"> <%= link_to "Log Out", destroy_user_session_path, method: :delete%></span>
        
        <% else %>
        <span class="btn btn-outline-primary"> <%= link_to "Log In",  new_user_session_path %></span>
        <span class="btn btn-outline-primary"> <%= link_to "Register Now",  new_user_registration_path %></span>
        
        <% end %>
      </nav>
    
    </div>

  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

    <%= yield %>
  </body>
</html>